gems:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:

array: []

# for SEO
webmaster_verifications:
  google: 6sqA5KNpZtZaQPB-78QcD8CDqXsbhOiqpZGvm NxYDI4
title: OpenROV Underwater Drones
description: Trident is the latest high performing underwater drone from OpenROV, makers of powerful tools for marine exploration.
url: 'https://www.openrov.com'

defaults:
  - scope:
      path: ""
    values:
      image: /images/openrov-trident-underwater-drone.jpg
      height: 1200
      width: 1200

#author:
#  twitter: openrov

twitter:
  username: openrov

social:
  name: OpenROV
  links:
    - https://twitter.com/OpenROV
    - https://www.facebook.com/OpenROV
    - https://www.instagram.com/openrov_hq
    - https://www.youtube.com/user/OpenROV

logo: /images/openrov.png

social:  


