- title: Ready to Dive
  image: ready-to-dive
  text: Trident comes ready to dive out of the box and is easy to control with any device.

- title: Full HD Camera
  image: hd-camera
  text: Underwater optimized, full HD camera with low latency offers 1080p video streaming and recording.

- title: Go to 100m 
  image: dive-to-100
  text: Trident can dive comfortably to 100m, far deeper than most recreational divers.

- title: 4 Hours Battery Life 
  image: battery
  text: Onboard rechargeable lithium batteries give you 4 hours of power to explore underwater.

- title: Wireless topside 
  image: wifi-topside
  text: Trident is equipped with a wireless topside unit for unprecedented connectivity.

- title: "Expandable &amp; Flexible"
  image: extendable
  text: "Trident features easy interface for upgrades, add-ons and modules."

