- title: Ready to Dive
  image: ready-to-dive
  text: Trident comes ready to dive out of the box and is easy to control with any device.

- title: Full HD Camera
  image: hd-camera
  text: Underwater optimized, full HD camera with low latency offers high quality video streaming and recording.

- title: Go to 100m 
  image: dive-to-100
  text: Trident can dive comfortably to 100m, far deeper than most recreational divers.

- title: 4 Hours Battery Life 
  image: battery
  text: Onboard rechargeable lithium batteries give you 4 hours of power to explore underwater.

- title: Radio Buoy 
  image: radio-buoy
  text: Trident is equipped with a towable Radio buoy for unprecedented freedom of movement.

- title: Expandable and Flexible
  image: extendable
  text: Trident features easy interface for upgrades, add-ons, and modules.

