- title: 'Chasis'
  content:
  - 'Weight: 3.3kg (7.3lbs)'
  - 'Dimensions: 86mm x 205mm x 410mm (3.4in x 8in x 16.1in)'
  - 'Depth rating: 100m (328ft)'
  - 'Neutrally buoyant in both fresh and saltwater (includes additional ballast)'
  - title: 'Hydrodynamic chassis design'
    items:
    - 'Speeds up to 4 knots (2m/s or 6.75ft/s)'
    - 'Tracks well in a straight line'
    - 'Able to pitch at high speeds'
    - 'Able to hover up and down at low speeds'
    - 'Rugged rubberized bumpers for protection and grip'

- title: 'Tether'
  content:
  - 'Breaking Strength: very strong - 1.1kN (247 lbf)'
  - 'Diameter: 4mm (0.16in)'
  - 'Neutrally buoyant in freshwater'
  - 'High visibility yellow'
  - 'Connectorized for easy tether management'
  - '25m (82ft) standard length'
  - '100m (328ft) length available'

- title: 'Payload'
  content:
  - 'Published and standard bolt pattern'
  - 'Modules and add-ons interface with the main vehicle via WiFi' 

- title: 'Lights'
  content:
  - '3 forward facing LEDs on each side'
  - 'Total lumens: 360'
  - 'Color temperature: 4000K'

- title: 'Radio Buoy'
  content:
  - 'Trident tows a buoy on the surface that can communicate wirelessly to your device'
  - 'Protocol: 802.11'
  - 'Range: ~30m (98ft)'
  
- title: 'Motors / Propellers'
  content: 
  - '3 brushless DC motors'
  - 'Ruggedized for low maintenance in seawater'
  - 'Electronic speed control matched with motors for optimal underwater performance'    

- title: 'Sensors'
  content: 
  - 'Inertial Movement Unit (IMU) with 3-axis gyro and 3-axis accelerometer'
  - 'Depth sensor'
  - 'Magnetometer (compass)'
  - 'Temperature'  


- title: 'Camera'
  content:
  - 'Resolution: 1080p'
  - 'Framerate: 30 fps'
  - 'Compression: onboard H.264 for easy streaming, recording, and storage'
  - 'High dynamic range (HDR)'
  - 'Excellent color rendition'
  - 'Wide angle'
  - 'Optimized for low light and underwater use'

- title: 'Batteries'
  content: 
  - 'AC adapter and charger included'
  - 'Chemistry: lithium manganese cobalt oxide (NMC)'
  - 'Capacity: 95Wh'
  - 'Average run time: 4 hours'
  - 'Average charge time: 2-3 hours'

- title: 'Software'
  content: 
  - 'System requirements: Any device able to run Google Chrome'
  - 'Device types: tablet, smartphone, or modern mobile device'
  - 'Control methods: game controller, joystick, keyboard, or touchscreen'
  - 'VR capable'
  - 'Customizable UI'
  - title: 'Computer assisted flight controls including'
    items: 
    - 'Gyro stabilization'
    - 'Depth hold'
    - 'Heading hold'